spring.application.name=soundwave-backend

spring.h2.console.enabled=true

spring.datasource.url=jdbc:mysql://176.9.90.24:3306/tobiasdo_Soundwave
spring.datasource.username=tobiasdo_soundwave
spring.datasource.password=soundwave123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
