name: Java CI + Docker Build

on:
  # Kør workflow når der pushes eller laves pull request til main
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      write-all

    steps:
      # Hent koden fra GitHub
      - name: Tjek projekt ud
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0
        with:
          persist-credentials: false

      # Sæt Java 21 op og cache Maven dependencies automatisk
      - name: Sæt JDK 21 op
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # Sørg for at mvnw kan køres på Linux
      - name: Gør Maven Wrapper eksekverbar
        run: chmod +x mvnw

      # Tjek at Maven Wrapper virker
      - name: Kontroller Maven Wrapper
        run: ./mvnw -v

      # Byg Java-projektet og kør tests
      - name: Byg projekt og kør tests
        run: ./mvnw -B verify

      # Sæt Buildx op til Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1


      # Login til GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Byg og push Docker image til GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/krymmel-kaemperne/soundwave-backend:latest
            ghcr.io/krymmel-kaemperne/soundwave-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
